# Generated by Django 4.0.3 on 2022-03-19 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('User_role_id', models.UUIDField(help_text='ID роли', primary_key=True, serialize=False)),
                ('User_role_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='UserReg',
            fields=[
                ('User_id', models.UUIDField(help_text='ID пользователя', primary_key=True, serialize=False)),
                ('First_name', models.CharField(help_text='Имя', max_length=50)),
                ('Middle_name', models.CharField(help_text='Отчество', max_length=50)),
                ('Last_name', models.CharField(help_text='Фамилия', max_length=50)),
                ('Email', models.EmailField(help_text='Почта', max_length=50)),
                ('Username', models.CharField(help_text='Ник', max_length=50)),
                ('User_password', models.CharField(help_text='Пароль', max_length=100)),
                ('Date_Registration', models.DateField(auto_now_add=True, help_text='Дата регистрации')),
                ('User_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.userrole')),
            ],
        ),
    ]
