# Generated by Django 4.0.3 on 2022-03-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0004_alter_userreg_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='User_id',
            field=models.IntegerField(help_text='ID пользователя', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='User_role_id',
            field=models.IntegerField(help_text='ID роли', primary_key=True, serialize=False),
        ),
    ]
