# Generated by Django 4.0.3 on 2022-03-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0006_manufacturer_alter_userreg_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionInt',
            fields=[
                ('ConnectionInt_id', models.AutoField(help_text='ID интерфейса подключения', primary_key=True, serialize=False, unique=True)),
                ('ConnectionInt_name', models.CharField(help_text='Интерфейс подключения', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectType',
            fields=[
                ('ConnectType_id', models.AutoField(help_text='ID типа подключения', primary_key=True, serialize=False, unique=True)),
                ('ConnectType_name', models.CharField(help_text='Тип подключения', max_length=50)),
            ],
        ),
    ]
