# Generated by Django 4.0.3 on 2022-03-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0012_h_headset_hz_h_headset_scheme_h_headset_sens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='h_headset_hz',
            name='H_HeadSet_Hz_Max_name',
            field=models.CharField(help_text='Максимальная воспроизводимая частота', max_length=50, null=True),
        ),
    ]
