# Generated by Django 4.0.3 on 2022-03-20 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0013_alter_h_headset_hz_h_headset_hz_max_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='h_headset',
            name='H_HeadSet_Image',
            field=models.ImageField(null=True, upload_to='Download/'),
        ),
        migrations.AddField(
            model_name='k_keyboard',
            name='K_Keyboard_Image',
            field=models.ImageField(null=True, upload_to='Download/'),
        ),
        migrations.AddField(
            model_name='m_mouse',
            name='M_Mouse_Image',
            field=models.ImageField(null=True, upload_to='Download/'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='Manufacturer_image',
            field=models.ImageField(null=True, upload_to='Download/'),
        ),
        migrations.AlterField(
            model_name='h_headset',
            name='H_HeadSet_ConnectType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.connecttype', verbose_name='Тип подключения'),
        ),
        migrations.AlterField(
            model_name='h_headset',
            name='H_HeadSet_ConnectionInt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.connectionint', verbose_name='Интерфейс подключения'),
        ),
        migrations.AlterField(
            model_name='h_headset',
            name='H_HeadSet_Hz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.h_headset_hz', verbose_name='Воспроизводимая частота'),
        ),
        migrations.AlterField(
            model_name='h_headset',
            name='H_HeadSet_Manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.manufacturer', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='h_headset',
            name='H_HeadSet_Scheme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.h_headset_scheme', verbose_name='Схема звука'),
        ),
        migrations.AlterField(
            model_name='h_headset',
            name='H_HeadSet_Sens',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.h_headset_sens', verbose_name='Чувствительность'),
        ),
        migrations.AlterField(
            model_name='h_headset',
            name='H_HeadSet_Set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.h_headset_set', verbose_name='Комплект'),
        ),
        migrations.AlterField(
            model_name='h_headset',
            name='H_HeadSet_name',
            field=models.CharField(help_text='Название гарнитуры', max_length=50, primary_key=True, serialize=False, verbose_name='Название гарнитуры'),
        ),
        migrations.AlterField(
            model_name='h_headset_hz',
            name='H_HeadSet_Hz_Max_name',
            field=models.CharField(help_text='Максимальная воспроизводимая частота', max_length=50, null=True, verbose_name='Максимальная воспроизводимая частота'),
        ),
        migrations.AlterField(
            model_name='h_headset_hz',
            name='H_HeadSet_Hz_Min_name',
            field=models.CharField(help_text='Минимальная воспроизводимая частота', max_length=50, null=True, verbose_name='Минимальная воспроизводимая частота'),
        ),
        migrations.AlterField(
            model_name='k_keyboard',
            name='K_Keyboard_ConnectType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.connecttype', verbose_name='Тип подключения'),
        ),
        migrations.AlterField(
            model_name='k_keyboard',
            name='K_Keyboard_ConnectionInt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.connectionint', verbose_name='Интерфейс подключения'),
        ),
        migrations.AlterField(
            model_name='k_keyboard',
            name='K_Keyboard_Format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.k_keyboard_format', verbose_name='Формат клавиатуры'),
        ),
        migrations.AlterField(
            model_name='k_keyboard',
            name='K_Keyboard_Manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.manufacturer', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='k_keyboard',
            name='K_Keyboard_SwitchModel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.k_keyboard_switchmodel', verbose_name='Модель переключателя'),
        ),
        migrations.AlterField(
            model_name='k_keyboard',
            name='K_Keyboard_Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.k_keyboard_type', verbose_name='Тип клавиатуры'),
        ),
        migrations.AlterField(
            model_name='k_keyboard',
            name='K_Keyboard_name',
            field=models.CharField(help_text='Название клавиатуры', max_length=50, primary_key=True, serialize=False, verbose_name='Название клавиатуры'),
        ),
        migrations.AlterField(
            model_name='m_mouse',
            name='M_Mouse_ConnectType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.connecttype', verbose_name='Тип подключения'),
        ),
        migrations.AlterField(
            model_name='m_mouse',
            name='M_Mouse_ConnectionInt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.connectionint', verbose_name='Интерфейс подключения'),
        ),
        migrations.AlterField(
            model_name='m_mouse',
            name='M_Mouse_DPI',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.m_mouse_dpi', verbose_name='Максимальное разрешение датчика'),
        ),
        migrations.AlterField(
            model_name='m_mouse',
            name='M_Mouse_Frequency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.m_mouse_frequency', verbose_name='Частота обращения'),
        ),
        migrations.AlterField(
            model_name='m_mouse',
            name='M_Mouse_Manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.manufacturer', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='m_mouse',
            name='M_Mouse_SenserModel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.m_mouse_sensermodel', verbose_name='Модель сенсора'),
        ),
        migrations.AlterField(
            model_name='m_mouse',
            name='M_Mouse_name',
            field=models.CharField(help_text='Название компьютерной мыши', max_length=50, primary_key=True, serialize=False, verbose_name='Название компьютерной мыши'),
        ),
    ]
