# Generated by Django 4.0.3 on 2022-03-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0015_alter_h_headset_h_headset_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='h_headset',
            name='H_HeadSet_Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='User_role_name',
            field=models.CharField(help_text='Название роли', max_length=15),
        ),
    ]
