# Generated by Django 4.0.3 on 2022-03-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0016_alter_h_headset_h_headset_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='M_Mouse',
        ),
    ]
