# Generated by Django 4.0.3 on 2022-03-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0018_m_mouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_mouse',
            name='M_Mouse_id',
            field=models.SlugField(help_text='ID компьютерной мыши', unique=True),
        ),
    ]
