# Generated by Django 4.0.3 on 2022-03-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0019_alter_m_mouse_m_mouse_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_mouse',
            name='M_Mouse_id',
            field=models.IntegerField(help_text='ID компьютерной мыши', unique=True),
        ),
    ]
