# Generated by Django 4.0.3 on 2022-03-21 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0022_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='m_mouse',
            old_name='M_Mouse_SenserModel',
            new_name='M_Mouse_SensModel',
        ),
    ]
