# Generated by Django 4.0.3 on 2022-03-21 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0023_rename_m_mouse_sensermodel_m_mouse_m_mouse_sensmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='m_mouse',
            old_name='M_Mouse_SensModel',
            new_name='M_Mouse_SenserModel',
        ),
    ]
