# Generated by Django 4.0.3 on 2022-03-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0025_alter_m_mouse_m_mouse_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='h_headset',
            name='H_HeadSet_id',
            field=models.AutoField(help_text='ID гарнитуры', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='k_keyboard',
            name='K_Keyboard_id',
            field=models.AutoField(help_text='ID клавиатуры', primary_key=True, serialize=False, unique=True),
        ),
    ]
