# Generated by Django 4.0.3 on 2022-03-22 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0027_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
