# Generated by Django 4.0.3 on 2022-03-22 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Site', '0028_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('Transaction_id', models.AutoField(help_text='ID транзакции', primary_key=True, serialize=False, unique=True)),
                ('Transaction_Date', models.DateField(auto_now_add=True, help_text='Дата транзакции')),
                ('Transaction_Headset', models.ForeignKey(help_text='Заказанная гарнитура', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.h_headset', verbose_name='Гарнитура')),
                ('Transaction_Keyboard', models.ForeignKey(help_text='Заказанная гарнитура', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.k_keyboard', verbose_name='Гарнитура')),
                ('Transaction_Mouse', models.ForeignKey(help_text='Заказанная гарнитура', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.m_mouse', verbose_name='Гарнитура')),
                ('Transaction_user', models.ForeignKey(blank=True, help_text='Покупатель продукции', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
        ),
    ]
