# Generated by Django 4.0.3 on 2022-03-22 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0029_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Transaction_Headset',
            field=models.ForeignKey(blank=True, help_text='Заказанная гарнитура', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.h_headset', verbose_name='Гарнитура'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Transaction_Keyboard',
            field=models.ForeignKey(blank=True, help_text='Заказанная гарнитура', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.k_keyboard', verbose_name='Гарнитура'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Transaction_Mouse',
            field=models.ForeignKey(blank=True, help_text='Заказанная гарнитура', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.m_mouse', verbose_name='Гарнитура'),
        ),
    ]
