# Generated by Django 4.0.3 on 2022-03-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0032_h_headset_h_headset_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='h_headset',
            name='H_HeadSet_Price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Цена клавиатуры'),
        ),
        migrations.AlterField(
            model_name='k_keyboard',
            name='K_Keyboard_Price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Цена клавиатуры'),
        ),
        migrations.AlterField(
            model_name='m_mouse',
            name='M_Mouse_Price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Цена компьютерной мышки'),
        ),
    ]
