# Generated by Django 4.0.3 on 2022-03-23 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Site', '0033_alter_h_headset_h_headset_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Transaction_Headset',
            field=models.ForeignKey(blank=True, help_text='Заказанная гарнитура', null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.h_headset', verbose_name='Гарнитура'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Transaction_Keyboard',
            field=models.ForeignKey(blank=True, help_text='Заказанная клавиатура', null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.k_keyboard', verbose_name='Клавиатура'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Transaction_Mouse',
            field=models.ForeignKey(blank=True, help_text='Заказанная компьютерная мышь', null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.m_mouse', verbose_name='Компьютерная мышь'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Transaction_user',
            field=models.ForeignKey(blank=True, help_text='Покупатель продукции', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
    ]
