# Generated by Django 4.0.3 on 2022-03-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0035_alter_h_headset_h_headset_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_mouse',
            name='M_Mouse_Price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена компьютерной мышки'),
        ),
    ]
