# Generated by Django 4.0.3 on 2022-04-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0036_alter_m_mouse_m_mouse_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_mouse',
            name='M_Mouse_Image',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads', verbose_name='Изображение модели'),
        ),
    ]
