# Generated by Django 4.0.3 on 2022-04-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0044_alter_m_mouse_m_mouse_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_mouse',
            name='M_Mouse_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название компьютерной мыши'),
        ),
    ]
