# Generated by Django 4.0.3 on 2022-04-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0045_alter_m_mouse_m_mouse_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='h_headset',
            name='H_HeadSet_name',
            field=models.CharField(max_length=50, verbose_name='Название гарнитуры'),
        ),
        migrations.AlterField(
            model_name='k_keyboard',
            name='K_Keyboard_name',
            field=models.CharField(max_length=50, verbose_name='Название клавиатуры'),
        ),
    ]
