# Generated by Django 4.0.3 on 2022-04-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0046_alter_h_headset_h_headset_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_mouse',
            name='M_Mouse_Price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Цена компьютерной мышки'),
        ),
    ]
