# Generated by Django 4.0.3 on 2022-04-29 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0047_alter_m_mouse_m_mouse_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
