# Generated by Django 4.0.3 on 2022-04-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0048_delete_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k_keyboard',
            name='K_Keyboard_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название клавиатуры'),
        ),
    ]
