# Generated by Django 4.0.3 on 2022-04-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0049_alter_k_keyboard_k_keyboard_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='h_headset',
            name='H_HeadSet_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название гарнитуры'),
        ),
    ]
